### PR TITLE
Integrates Circle CI and Bixby into new application (#23).

### PR DESCRIPTION
**Pull request by bwatson78**
Actions performed: 
1. Installs Bixby (Hyrax-friendly Rubocop).
2. Installs Rspec.
3. Installs Coveralls.
4. Creates test instance of SolrWrapper.
5. Removes MiniTest structure.
6. Wires Selenium:Webdriver headless Chrome to Capybara.
7. Lints all application files to Bixby standards.

### CODE REVIEW

**Comment by devanshu-m** [comment]
Looks good. Should we change the title? Since, there is no circle ci setup in this PR.

**Comment by bwatson78** [comment]
From what I gather from Lux' ticket revolving around CI is that it's just making sure that a Rspec and Rubocop structure in place, and then the integration of CI comes from interacting with Github once that code's in main.

**Comment by devanshu-m** [comment]
Correct, but I think we still need a circle ci config yml? 

Refer: 
https://github.com/emory-libraries/dlp-lux/blob/main/.circleci/config.yml
https://circleci.com/docs/2.0/getting-started/

**Comment by bwatson78** [comment]
@devanshu-m You're right. Somehow, I missed the creation of that file.

**Comment by bwatson78** [comment]
Working on it now.

**Comment by bwatson78** [comment]
@devanshu-m I have pushed up the new code for the config file. I can't go any further in the CircleCI process since I'm not an Admin at that page.

**Comment by devanshu-m** [comment]
@rotated8 @alexBLR can either of you help with setting up this repo for circleci; checking the main branch and PRs? I don't have admin access either.

**Comment by rotated8** [comment]
@devanshu-m @bwatson78 I added the project on the CircleCI side.

**Comment by bwatson78** [comment]
@devanshu-m I think we have to actually merge it into main before we can see it work on the repo. I clicked the link on the README and found that it wouldn't recognize the config.yml file yet. If you agree, can you merge this or give me the thumbs to merge it myself?

**Review by devanshu-m — APPROVED** [review]

**Pull request merged**
